services:
  mysql_server:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db
      MYSQL_USER: thesyd
      MYSQL_PASSWORD: 1234
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: mysql_server
    depends_on:
      - mysql_server

volumes:
  mysql-data:
